/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class AAssignStatement extends PStatement
{
    private TQuotedText _quotedText_;
    private PExpression _expression_;
    private TAssignArrow _assignArrow_;
    private TVariableName _variableName_;
    private TPrintResult _printResult_;

    public AAssignStatement()
    {
        // Constructor
    }

    public AAssignStatement(
        @SuppressWarnings("hiding") TQuotedText _quotedText_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TAssignArrow _assignArrow_,
        @SuppressWarnings("hiding") TVariableName _variableName_,
        @SuppressWarnings("hiding") TPrintResult _printResult_)
    {
        // Constructor
        setQuotedText(_quotedText_);

        setExpression(_expression_);

        setAssignArrow(_assignArrow_);

        setVariableName(_variableName_);

        setPrintResult(_printResult_);

    }

    @Override
    public Object clone()
    {
        return new AAssignStatement(
            cloneNode(this._quotedText_),
            cloneNode(this._expression_),
            cloneNode(this._assignArrow_),
            cloneNode(this._variableName_),
            cloneNode(this._printResult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStatement(this);
    }

    public TQuotedText getQuotedText()
    {
        return this._quotedText_;
    }

    public void setQuotedText(TQuotedText node)
    {
        if(this._quotedText_ != null)
        {
            this._quotedText_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._quotedText_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TAssignArrow getAssignArrow()
    {
        return this._assignArrow_;
    }

    public void setAssignArrow(TAssignArrow node)
    {
        if(this._assignArrow_ != null)
        {
            this._assignArrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignArrow_ = node;
    }

    public TVariableName getVariableName()
    {
        return this._variableName_;
    }

    public void setVariableName(TVariableName node)
    {
        if(this._variableName_ != null)
        {
            this._variableName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableName_ = node;
    }

    public TPrintResult getPrintResult()
    {
        return this._printResult_;
    }

    public void setPrintResult(TPrintResult node)
    {
        if(this._printResult_ != null)
        {
            this._printResult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._printResult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._quotedText_)
            + toString(this._expression_)
            + toString(this._assignArrow_)
            + toString(this._variableName_)
            + toString(this._printResult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._quotedText_ == child)
        {
            this._quotedText_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._assignArrow_ == child)
        {
            this._assignArrow_ = null;
            return;
        }

        if(this._variableName_ == child)
        {
            this._variableName_ = null;
            return;
        }

        if(this._printResult_ == child)
        {
            this._printResult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._quotedText_ == oldChild)
        {
            setQuotedText((TQuotedText) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._assignArrow_ == oldChild)
        {
            setAssignArrow((TAssignArrow) newChild);
            return;
        }

        if(this._variableName_ == oldChild)
        {
            setVariableName((TVariableName) newChild);
            return;
        }

        if(this._printResult_ == oldChild)
        {
            setPrintResult((TPrintResult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
