/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class AFactorialAtom extends PAtom
{
    private PAtom _atom_;
    private TBang _bang_;

    public AFactorialAtom()
    {
        // Constructor
    }

    public AFactorialAtom(
        @SuppressWarnings("hiding") PAtom _atom_,
        @SuppressWarnings("hiding") TBang _bang_)
    {
        // Constructor
        setAtom(_atom_);

        setBang(_bang_);

    }

    @Override
    public Object clone()
    {
        return new AFactorialAtom(
            cloneNode(this._atom_),
            cloneNode(this._bang_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFactorialAtom(this);
    }

    public PAtom getAtom()
    {
        return this._atom_;
    }

    public void setAtom(PAtom node)
    {
        if(this._atom_ != null)
        {
            this._atom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atom_ = node;
    }

    public TBang getBang()
    {
        return this._bang_;
    }

    public void setBang(TBang node)
    {
        if(this._bang_ != null)
        {
            this._bang_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bang_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atom_)
            + toString(this._bang_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atom_ == child)
        {
            this._atom_ = null;
            return;
        }

        if(this._bang_ == child)
        {
            this._bang_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atom_ == oldChild)
        {
            setAtom((PAtom) newChild);
            return;
        }

        if(this._bang_ == oldChild)
        {
            setBang((TBang) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
