/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class AFuncNoArgsFunc extends PFunc
{
    private TFunctionNoargsName _functionNoargsName_;

    public AFuncNoArgsFunc()
    {
        // Constructor
    }

    public AFuncNoArgsFunc(
        @SuppressWarnings("hiding") TFunctionNoargsName _functionNoargsName_)
    {
        // Constructor
        setFunctionNoargsName(_functionNoargsName_);

    }

    @Override
    public Object clone()
    {
        return new AFuncNoArgsFunc(
            cloneNode(this._functionNoargsName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncNoArgsFunc(this);
    }

    public TFunctionNoargsName getFunctionNoargsName()
    {
        return this._functionNoargsName_;
    }

    public void setFunctionNoargsName(TFunctionNoargsName node)
    {
        if(this._functionNoargsName_ != null)
        {
            this._functionNoargsName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionNoargsName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionNoargsName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionNoargsName_ == child)
        {
            this._functionNoargsName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._functionNoargsName_ == oldChild)
        {
            setFunctionNoargsName((TFunctionNoargsName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
