/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class AMultgroupFactor extends PFactor
{
    private PFactor _factor_;
    private PMultgroup _multgroup_;

    public AMultgroupFactor()
    {
        // Constructor
    }

    public AMultgroupFactor(
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") PMultgroup _multgroup_)
    {
        // Constructor
        setFactor(_factor_);

        setMultgroup(_multgroup_);

    }

    @Override
    public Object clone()
    {
        return new AMultgroupFactor(
            cloneNode(this._factor_),
            cloneNode(this._multgroup_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultgroupFactor(this);
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public PMultgroup getMultgroup()
    {
        return this._multgroup_;
    }

    public void setMultgroup(PMultgroup node)
    {
        if(this._multgroup_ != null)
        {
            this._multgroup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multgroup_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factor_)
            + toString(this._multgroup_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._multgroup_ == child)
        {
            this._multgroup_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._multgroup_ == oldChild)
        {
            setMultgroup((PMultgroup) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
