/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class ANegateFactor extends PFactor
{
    private TMinus _minus_;
    private PMultgroup _multgroup_;

    public ANegateFactor()
    {
        // Constructor
    }

    public ANegateFactor(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PMultgroup _multgroup_)
    {
        // Constructor
        setMinus(_minus_);

        setMultgroup(_multgroup_);

    }

    @Override
    public Object clone()
    {
        return new ANegateFactor(
            cloneNode(this._minus_),
            cloneNode(this._multgroup_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegateFactor(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PMultgroup getMultgroup()
    {
        return this._multgroup_;
    }

    public void setMultgroup(PMultgroup node)
    {
        if(this._multgroup_ != null)
        {
            this._multgroup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multgroup_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._multgroup_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._multgroup_ == child)
        {
            this._multgroup_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._multgroup_ == oldChild)
        {
            setMultgroup((PMultgroup) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
