/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class APostfixopMultgroup extends PMultgroup
{
    private PPostfixop _postfixop_;

    public APostfixopMultgroup()
    {
        // Constructor
    }

    public APostfixopMultgroup(
        @SuppressWarnings("hiding") PPostfixop _postfixop_)
    {
        // Constructor
        setPostfixop(_postfixop_);

    }

    @Override
    public Object clone()
    {
        return new APostfixopMultgroup(
            cloneNode(this._postfixop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostfixopMultgroup(this);
    }

    public PPostfixop getPostfixop()
    {
        return this._postfixop_;
    }

    public void setPostfixop(PPostfixop node)
    {
        if(this._postfixop_ != null)
        {
            this._postfixop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._postfixop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._postfixop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._postfixop_ == child)
        {
            this._postfixop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._postfixop_ == oldChild)
        {
            setPostfixop((PPostfixop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
