/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class APowerMultgroup extends PMultgroup
{
    private PMultgroup _multgroup_;
    private TPow _pow_;
    private PPostfixop _postfixop_;

    public APowerMultgroup()
    {
        // Constructor
    }

    public APowerMultgroup(
        @SuppressWarnings("hiding") PMultgroup _multgroup_,
        @SuppressWarnings("hiding") TPow _pow_,
        @SuppressWarnings("hiding") PPostfixop _postfixop_)
    {
        // Constructor
        setMultgroup(_multgroup_);

        setPow(_pow_);

        setPostfixop(_postfixop_);

    }

    @Override
    public Object clone()
    {
        return new APowerMultgroup(
            cloneNode(this._multgroup_),
            cloneNode(this._pow_),
            cloneNode(this._postfixop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPowerMultgroup(this);
    }

    public PMultgroup getMultgroup()
    {
        return this._multgroup_;
    }

    public void setMultgroup(PMultgroup node)
    {
        if(this._multgroup_ != null)
        {
            this._multgroup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multgroup_ = node;
    }

    public TPow getPow()
    {
        return this._pow_;
    }

    public void setPow(TPow node)
    {
        if(this._pow_ != null)
        {
            this._pow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pow_ = node;
    }

    public PPostfixop getPostfixop()
    {
        return this._postfixop_;
    }

    public void setPostfixop(PPostfixop node)
    {
        if(this._postfixop_ != null)
        {
            this._postfixop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._postfixop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multgroup_)
            + toString(this._pow_)
            + toString(this._postfixop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multgroup_ == child)
        {
            this._multgroup_ = null;
            return;
        }

        if(this._pow_ == child)
        {
            this._pow_ = null;
            return;
        }

        if(this._postfixop_ == child)
        {
            this._postfixop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multgroup_ == oldChild)
        {
            setMultgroup((PMultgroup) newChild);
            return;
        }

        if(this._pow_ == oldChild)
        {
            setPow((TPow) newChild);
            return;
        }

        if(this._postfixop_ == oldChild)
        {
            setPostfixop((PPostfixop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
