/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class APowerPow extends PPow
{
    private PPow _left_;
    private TPow _op_;
    private PPostfixop _right_;

    public APowerPow()
    {
        // Constructor
    }

    public APowerPow(
        @SuppressWarnings("hiding") PPow _left_,
        @SuppressWarnings("hiding") TPow _op_,
        @SuppressWarnings("hiding") PPostfixop _right_)
    {
        // Constructor
        setLeft(_left_);

        setOp(_op_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new APowerPow(
            cloneNode(this._left_),
            cloneNode(this._op_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPowerPow(this);
    }

    public PPow getLeft()
    {
        return this._left_;
    }

    public void setLeft(PPow node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TPow getOp()
    {
        return this._op_;
    }

    public void setOp(TPow node)
    {
        if(this._op_ != null)
        {
            this._op_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op_ = node;
    }

    public PPostfixop getRight()
    {
        return this._right_;
    }

    public void setRight(PPostfixop node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._op_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._op_ == child)
        {
            this._op_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PPow) newChild);
            return;
        }

        if(this._op_ == oldChild)
        {
            setOp((TPow) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PPostfixop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
