/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class ASequenceProgram extends PProgram
{
    private PStatement _statement_;
    private TNewline _newline_;
    private PProgram _program_;

    public ASequenceProgram()
    {
        // Constructor
    }

    public ASequenceProgram(
        @SuppressWarnings("hiding") PStatement _statement_,
        @SuppressWarnings("hiding") TNewline _newline_,
        @SuppressWarnings("hiding") PProgram _program_)
    {
        // Constructor
        setStatement(_statement_);

        setNewline(_newline_);

        setProgram(_program_);

    }

    @Override
    public Object clone()
    {
        return new ASequenceProgram(
            cloneNode(this._statement_),
            cloneNode(this._newline_),
            cloneNode(this._program_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceProgram(this);
    }

    public PStatement getStatement()
    {
        return this._statement_;
    }

    public void setStatement(PStatement node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    public TNewline getNewline()
    {
        return this._newline_;
    }

    public void setNewline(TNewline node)
    {
        if(this._newline_ != null)
        {
            this._newline_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newline_ = node;
    }

    public PProgram getProgram()
    {
        return this._program_;
    }

    public void setProgram(PProgram node)
    {
        if(this._program_ != null)
        {
            this._program_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._program_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._statement_)
            + toString(this._newline_)
            + toString(this._program_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        if(this._newline_ == child)
        {
            this._newline_ = null;
            return;
        }

        if(this._program_ == child)
        {
            this._program_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

        if(this._newline_ == oldChild)
        {
            setNewline((TNewline) newChild);
            return;
        }

        if(this._program_ == oldChild)
        {
            setProgram((PProgram) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
