/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class ASinglePow extends PPow
{
    private PPostfixop _single_;

    public ASinglePow()
    {
        // Constructor
    }

    public ASinglePow(
        @SuppressWarnings("hiding") PPostfixop _single_)
    {
        // Constructor
        setSingle(_single_);

    }

    @Override
    public Object clone()
    {
        return new ASinglePow(
            cloneNode(this._single_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinglePow(this);
    }

    public PPostfixop getSingle()
    {
        return this._single_;
    }

    public void setSingle(PPostfixop node)
    {
        if(this._single_ != null)
        {
            this._single_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._single_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._single_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._single_ == child)
        {
            this._single_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._single_ == oldChild)
        {
            setSingle((PPostfixop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
