/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class ASubStatement extends PStatement
{
    private TProg _prog_;
    private TSpace _space_;
    private TQuotedText _quotedText_;

    public ASubStatement()
    {
        // Constructor
    }

    public ASubStatement(
        @SuppressWarnings("hiding") TProg _prog_,
        @SuppressWarnings("hiding") TSpace _space_,
        @SuppressWarnings("hiding") TQuotedText _quotedText_)
    {
        // Constructor
        setProg(_prog_);

        setSpace(_space_);

        setQuotedText(_quotedText_);

    }

    @Override
    public Object clone()
    {
        return new ASubStatement(
            cloneNode(this._prog_),
            cloneNode(this._space_),
            cloneNode(this._quotedText_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubStatement(this);
    }

    public TProg getProg()
    {
        return this._prog_;
    }

    public void setProg(TProg node)
    {
        if(this._prog_ != null)
        {
            this._prog_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prog_ = node;
    }

    public TSpace getSpace()
    {
        return this._space_;
    }

    public void setSpace(TSpace node)
    {
        if(this._space_ != null)
        {
            this._space_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._space_ = node;
    }

    public TQuotedText getQuotedText()
    {
        return this._quotedText_;
    }

    public void setQuotedText(TQuotedText node)
    {
        if(this._quotedText_ != null)
        {
            this._quotedText_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._quotedText_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prog_)
            + toString(this._space_)
            + toString(this._quotedText_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prog_ == child)
        {
            this._prog_ = null;
            return;
        }

        if(this._space_ == child)
        {
            this._space_ = null;
            return;
        }

        if(this._quotedText_ == child)
        {
            this._quotedText_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prog_ == oldChild)
        {
            setProg((TProg) newChild);
            return;
        }

        if(this._space_ == oldChild)
        {
            setSpace((TSpace) newChild);
            return;
        }

        if(this._quotedText_ == oldChild)
        {
            setQuotedText((TQuotedText) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
