/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class TGoto extends Token
{
    public TGoto()
    {
        super.setText("Goto ");
    }

    public TGoto(int line, int pos)
    {
        super.setText("Goto ");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGoto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGoto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGoto text.");
    }
}
