/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.node;

import org.bradders.casiocfx9800g.analysis.*;

@SuppressWarnings("nls")
public final class TProg extends Token
{
    public TProg()
    {
        super.setText("Prog");
    }

    public TProg(int line, int pos)
    {
        super.setText("Prog");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProg(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProg(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProg text.");
    }
}
