Run('fx-9860g-emulator/NewGraph.exe', 'fx-9860g-emulator')
WinWait('NewGraph', '', 1)
WinActivate('NewGraph')
$pos = WinGetPos('[ACTIVE]')
$x = $pos[0]
$y = $pos[1]

Send('B') ; open program menu
Send('{F3}') ; start new prog
; Send the program name in lowercase to avoid a strange ALPHA-LOCK behaviour
Send('powerseqs{ENTER}') ; file name - at most 8 chars

; program text starts here

Send('"POWER SEQS"{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('"POWER? (2-3)"{ENTER}')
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('A{ENTER}')
Send('A=2{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('2{ENTER}')
Send('A=3{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('3{ENTER}')
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('2{ENTER}')
Send('"QUADRATIC:"{ENTER}')
Send('"ENTER THE FIRST"{ENTER}')
Send('"THREE NUMBERS"{ENTER}')
Send('"N=1"{ENTER}')
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('U{ENTER}')
Send('"N=2"{ENTER}')
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('V{ENTER}')
Send('"N=3"{ENTER}')
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('W{ENTER}')
Send('W-V')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('Q{ENTER}')
Send('V-U')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('P{ENTER}')
Send('Q-P')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('G{ENTER}')
Send('G*0.5')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('A{ENTER}')
Send('P-3A')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('B{ENTER}')
Send('U-A-B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('C{ENTER}')
Send('"F(N)=AN{^}2{+}BN{+}C"{ENTER}')
Send('"A="{ENTER}')
Send('A')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F5}') ; print result (state is ["PRGM"])
Send('"B="{ENTER}')
Send('B{F5}') ; print result (state is ["PRGM"])
Send('"C="{ENTER}')
Send('C{F5}') ; print result (state is ["PRGM"])
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('9{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('3{ENTER}')
Send('"CUBIC:"{ENTER}')
Send('"ENTER THE FIRST FOUR NUMBERS"{ENTER}')
Send('"N=1"{ENTER}')
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('U{ENTER}')
Send('"N=2"{ENTER}')
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('V{ENTER}')
Send('"N=3"{ENTER}')
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('W{ENTER}')
Send('"N=4"{ENTER}')
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('X{ENTER}')
Send('(X-W)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('R{ENTER}')
Send('(W-V)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('Q{ENTER}')
Send('(V-U)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('P{ENTER}')
Send('(R-Q)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('N{ENTER}')
Send('(Q-P)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('M{ENTER}')
Send('(N-M)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('J{ENTER}')
Send('(M-(2J))')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('I{ENTER}')
Send('(U-P{+}M-J)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('G{ENTER}')
Send('G')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('A{ENTER}')
Send('(I*1')
MouseClick('left', $x + 73, $y + 487) ; fraction (state is PRGM -> JUMP)
Send('2)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('C{ENTER}')
Send('(J*1')
MouseClick('left', $x + 73, $y + 487) ; fraction (state is PRGM -> JUMP)
Send('6)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('D{ENTER}')
Send('(U-A-C-D)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('B{ENTER}')
Send('"AN{^}3{+}BN{^}2{+}CN{+}D:"{ENTER}')
Send('"A="{ENTER}')
Send('D')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F5}') ; print result (state is ["PRGM"])
Send('"B="{ENTER}')
Send('C{F5}') ; print result (state is ["PRGM"])
Send('"C="{ENTER}')
Send('B{F5}') ; print result (state is ["PRGM"])
Send('"D="{ENTER}')
Send('A{F5}') ; print result (state is ["PRGM"])
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('9{ENTER}')

; end program text

MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM -> JUMP)
MouseClick('left', $x + 202, $y + 413) ; QUIT (state is PRGM -> JUMP)
Send('{F1}') ; EXE
