Run('fx-9860g-emulator/NewGraph.exe', 'fx-9860g-emulator')
WinWait('NewGraph', '', 1)
WinActivate('NewGraph')
$pos = WinGetPos('[ACTIVE]')
$x = $pos[0]
$y = $pos[1]

Send('B') ; open program menu
Send('{F3}') ; start new prog
; Send the program name in lowercase to avoid a strange ALPHA-LOCK behaviour
Send('bse{ENTER}') ; file name - at most 8 chars

; program text starts here

Send('"BSE"{ENTER}')
Send('0')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('T{ENTER}')
Send('600')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('S{ENTER}')
Send('100')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('B{ENTER}')
Send('0')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('C{ENTER}')
Send('500')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('F{ENTER}')
Send('1')
MouseClick('left', $x + 73, $y + 487) ; fraction
Send('2')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('G{ENTER}')
Send('0')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('K{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('C{+}((')
MouseClick('left', $x + 117, $y + 376) ; OPTN (state is OPTN)
Send('{F6}') ; more (state is ["OPTN", "more"])
Send('{F4}') ; NUM (state is ["OPTN", "more", "NUM"])
Send('{F2}') ; Int  (state is ["OPTN", "more", "NUM"])
Send('(')
MouseClick('left', $x + 117, $y + 376) ; OPTN (state is OPTN)
Send('{F6}') ; more (state is ["OPTN", "more"])
Send('{F3}') ; PROB (state is ["OPTN", "more", "PROB"])
Send('{F4}') ; Ran# (state is ["OPTN", "more", "PROB"])
Send('*100)){+}25)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is OPTN -> more -> PROB)
Send('C{ENTER}')
Send('T{+}C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is OPTN -> more -> PROB)
Send('T{ENTER}')
Send('"YOU HAVE:"{ENTER}')
Send('"COWS=":C')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F5}') ; print result (state is ["PRGM"])
Send('"FUNDS PER WEEK=":F{F5}') ; print result (state is ["PRGM"])
Send('"GOVT HAPPYNESS=":G{F5}') ; print result (state is ["PRGM"])
Send('"KILLIN CAPACITY":"PER WEEK=":K{F5}') ; print result (state is ["PRGM"])
Send('"BARN SPACES=":B{F5}') ; print result (state is ["PRGM"])
Send('"MONEY=":S{F5}') ; print result (state is ["PRGM"])
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('2:"YOU CAN KILL="{ENTER}')
Send('S/5')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F6}') ; more (state is ["PRGM", "more"])
Send('{F3}') ; REL (state is ["PRGM", "more", "REL"])
Send('{F6}') ; <= (state is ["PRGM", "more", "REL"])
Send('C')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('S')
MouseClick('left', $x + 73, $y + 487) ; fraction (state is PRGM -> JUMP)
Send('5')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('D{ENTER}')
Send('C<S/5{F3}') ; => (state is ["PRGM", "JUMP"])
Send('C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('D{ENTER}')
Send('K<D{F3}') ; => (state is ["PRGM", "JUMP"])
Send('K')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('D{ENTER}')
Send('D')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F5}') ; print result (state is ["PRGM"])
Send('"HOW MANY DO YOU"{ENTER}')
Send('"WANT TO KILL"?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM)
Send('L{ENTER}')
Send('L>D')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('2{ENTER}')
Send('S-(L*5)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('S{ENTER}')
Send('C-L')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('C{ENTER}')
Send('"HOW MANY MORE":"ABATOIRE SPACES":"DO YOU WANT TO":"BUY?"{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('3:"YOU CAN BUY"{ENTER}')
Send('S')
MouseClick('left', $x + 73, $y + 487) ; fraction (state is PRGM -> JUMP)
Send('5')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F5}') ; print result (state is ["PRGM"])
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM)
Send('L{ENTER}')
Send('L>(S/5)')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('3{ENTER}')
Send('K{+}L')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('K:S-(L*5)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('S{ENTER}')
Send('"HOW MANY BARN"{ENTER}')
Send('"SPACES DO YOU"{ENTER}')
Send('"WANT TO BUY?"{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('4:"YOU CAN BUY":S')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F5}') ; print result (state is ["PRGM"])
Send('?')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM)
Send('L:L>S')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('4{ENTER}')
Send('S-L')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('S:B{+}L')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('B{ENTER}')
Send('S-(C*5)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('S{ENTER}')
Send('G{+}((B-C)/200)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('G{ENTER}')
Send('G<0{F3}') ; => (state is ["PRGM", "JUMP"])
Send('0')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('G:G>1{F3}') ; => (state is ["PRGM", "JUMP"])
Send('1')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('G{ENTER}')
Send('((G-1')
MouseClick('left', $x + 73, $y + 487) ; fraction (state is PRGM -> JUMP)
Send('2)*100){+}F')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('F{ENTER}')
Send('S{+}F')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('S{ENTER}')
Send('"==NEXT YEAR=="{ENTER}')
Send('T')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F6}') ; more (state is ["PRGM", "more"])
Send('{F3}') ; REL (state is ["PRGM", "more", "REL"])
Send('{F5}') ; >= (state is ["PRGM", "more", "REL"])
Send('1000')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('8{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('6{ENTER}')
Send('S')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F6}') ; more (state is ["PRGM", "more"])
Send('{F3}') ; REL (state is ["PRGM", "more", "REL"])
Send('{F5}') ; >= (state is ["PRGM", "more", "REL"])
Send('-100')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('"YOU ARE IN DEBT"{ENTER}')
Send('"BY"{ENTER}')
Send('S*-1')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F5}') ; print result (state is ["PRGM"])
Send('"YOURE"{ENTER}')
Send('"FF I RR  EE DD "{ENTER}')
Send('"F  I R R E  D D"{ENTER}')
Send('"F  I R R E  D D"{ENTER}')
Send('"FF I RR  EE D D"{ENTER}')
Send('"F  I R R E  D D"{ENTER}')
Send('"F  I R R E  D D"{ENTER}')
Send('"F  I R R EE DD"{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('9{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('8{ENTER}')
Send('C>0{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('6{ENTER}')
Send('"YOU HAVE"{ENTER}')
Send('"W   W  OO  N  N"{ENTER}')
Send('"W   W O  O NN N"{ENTER}')
Send('"W W W O  O N NN"{ENTER}')
Send('" W W   OO  N  N"{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('9{ENTER}')

; end program text

MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM -> JUMP)
MouseClick('left', $x + 202, $y + 413) ; QUIT (state is PRGM -> JUMP)
Send('{F1}') ; EXE
