Run('fx-9860g-emulator/NewGraph.exe', 'fx-9860g-emulator')
WinWait('NewGraph', '', 1)
WinActivate('NewGraph')
$pos = WinGetPos('[ACTIVE]')
$x = $pos[0]
$y = $pos[1]

Send('B') ; open program menu
Send('{F3}') ; start new prog
; Send the program name in lowercase to avoid a strange ALPHA-LOCK behaviour
Send('jack{ENTER}') ; file name - at most 8 chars

; program text starts here

Send('"UNION JACK"{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT
Send('{F3}{F1}') ; ViewWindow
Send('1,1.95,100,1,1.63,100{ENTER}')
Send('1.47')
MouseClick('left', $x + 290, $y + 487) ; ->
MouseClick('left', $x + 73, $y + 413) ; ALPHA
MouseClick('left', $x + 117, $y + 413) ; rho
Send(':1.315')
MouseClick('left', $x + 290, $y + 487) ; ->
MouseClick('left', $x + 73, $y + 413) ; ALPHA
MouseClick('left', $x + 159, $y + 413) ; theta
Send(':2')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('A:1')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('B:1.31')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('C:1.95')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('D:1.31')
MouseClick('left', $x + 290, $y + 487) ; ->
Send('E{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F2}') ; CTL (state is ["PRGM", "CTL"])
Send('{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE"{ENTER}')
Send('1.32')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('C:C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('E:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":1.30')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('C:C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('E:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":1.33')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('C:C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('E:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":1.29')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('C:C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('E:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE"{ENTER}')
Send('1.47')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:1')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('C:B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:1.63')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('E:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":1.46')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":1.48')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":1.45')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":1.49')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE"{ENTER}')
Send('2')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('A:0')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('G:1')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('H:1')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('I:1.43')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('J:1.27')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('K{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('H')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('B:I')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('C:J')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('D:K')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('E:')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F2}') ; CTL (state is ["PRGM", "CTL"])
Send('{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":2.95-B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:2.95-D')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":2.63-C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('C:2.63-E')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('E:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE":2.95-B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:2.95-D')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE"{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F4}') ; Isz  (state is ["PRGM", "JUMP"])
Send('G{ENTER}')
Send('G')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F6}') ; more (state is ["PRGM", "more"])
Send('{F3}') ; REL (state is ["PRGM", "more", "REL"])
Send('{F2}') ; != (state is ["PRGM", "more", "REL"])
Send('1')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('2{ENTER}')
Send('1.26')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('K:1.01')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('H:{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('2:G')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F6}') ; more (state is ["PRGM", "more"])
Send('{F3}') ; REL (state is ["PRGM", "more", "REL"])
Send('{F2}') ; != (state is ["PRGM", "more", "REL"])
Send('2')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('3:1.25')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('K:1.02')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('H:{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('3:G')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F6}') ; more (state is ["PRGM", "more"])
Send('{F3}') ; REL (state is ["PRGM", "more", "REL"])
Send('{F2}') ; != (state is ["PRGM", "more", "REL"])
Send('3')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('4:1.27')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('K:1.42')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('J:1')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('H:1.01')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('I:{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('4:G')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F6}') ; more (state is ["PRGM", "more"])
Send('{F3}') ; REL (state is ["PRGM", "more", "REL"])
Send('{F2}') ; != (state is ["PRGM", "more", "REL"])
Send('4')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('5:1.02')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('I:1.41')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('J:{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('1{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('5{ENTER}')
Send('1')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('A:1.43')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('B:B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('P:1.40')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('C:C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('Q:0')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('W:0')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('L:B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('D:D')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('R:1.63')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('E:E')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('S:1.375')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('M:1.35')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('N:1.375')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('U:1.34')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('V{ENTER}')
Send('{F1}') ; Lbl  (state is ["PRGM", "JUMP"])
Send('6{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F2}') ; CTL (state is ["PRGM", "CTL"])
Send('{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE"{ENTER}')
Send('2')
MouseClick('left', $x + 73, $y + 413) ; ALPHA (state is PRGM -> CTL)
MouseClick('left', $x + 117, $y + 413) ; rho (state is PRGM -> CTL)
Send('-B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:2')
MouseClick('left', $x + 73, $y + 413) ; ALPHA (state is PRGM -> CTL)
MouseClick('left', $x + 117, $y + 413) ; rho (state is PRGM -> CTL)
Send('-D')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE"{ENTER}')
Send('2')
MouseClick('left', $x + 73, $y + 413) ; ALPHA (state is PRGM -> CTL)
MouseClick('left', $x + 159, $y + 413) ; theta (state is PRGM -> CTL)
Send('-C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('C:2')
MouseClick('left', $x + 73, $y + 413) ; ALPHA (state is PRGM -> CTL)
MouseClick('left', $x + 159, $y + 413) ; theta (state is PRGM -> CTL)
Send('-E')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('E:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE"{ENTER}')
Send('2')
MouseClick('left', $x + 73, $y + 413) ; ALPHA (state is PRGM -> CTL)
MouseClick('left', $x + 117, $y + 413) ; rho (state is PRGM -> CTL)
Send('-B')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:2')
MouseClick('left', $x + 73, $y + 413) ; ALPHA (state is PRGM -> CTL)
MouseClick('left', $x + 117, $y + 413) ; rho (state is PRGM -> CTL)
Send('-D')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:{F1}') ; Prog (state is ["PRGM", "CTL"])
Send('"LINE"{ENTER}')
Send('L{+}0.5')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('L{ENTER}')
Send('M-0.006*0.38/(1.57-')
MouseClick('left', $x + 73, $y + 413) ; ALPHA (state is PRGM -> CTL)
MouseClick('left', $x + 159, $y + 413) ; theta (state is PRGM -> CTL)
Send(')')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('M:M')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('B:N{+}0.005')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('N:N')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('C:0')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('D:C')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> CTL)
Send('E{ENTER}')
MouseClick('left', $x + 117, $y + 376) ; OPTN (state is OPTN)
Send('{F6}') ; more (state is ["OPTN", "more"])
Send('{F4}') ; NUM (state is ["OPTN", "more", "NUM"])
Send('{F3}') ; Frac  (state is ["OPTN", "more", "NUM"])
Send('L=0.5')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('6{ENTER}')
Send('{F4}') ; Isz  (state is ["PRGM", "JUMP"])
Send('W{ENTER}')
Send('P-0.01')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('P:P')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('B:P')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('R:P')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('D:Q{+}0.01*(1.63-1.40)/(1.43-1.06)')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('Q:Q')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('C:S')
MouseClick('left', $x + 290, $y + 487) ; -> (state is PRGM -> JUMP)
Send('E{ENTER}')
Send('W')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F6}') ; more (state is ["PRGM", "more"])
Send('{F3}') ; REL (state is ["PRGM", "more", "REL"])
Send('{F6}') ; <= (state is ["PRGM", "more", "REL"])
Send('39')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
Send('{F2}') ; Goto  (state is ["PRGM", "JUMP"])
Send('6{ENTER}')

; end program text

MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM -> JUMP)
MouseClick('left', $x + 202, $y + 413) ; QUIT (state is PRGM -> JUMP)
Send('{F3}') ; start new prog
; Send the program name in lowercase to avoid a strange ALPHA-LOCK behaviour
Send('line{ENTER}') ; file name - at most 8 chars

; program text starts here

MouseClick('left', $x + 73, $y + 376) ; SHIFT
Send('{F4}{F6}{F1}{F1}') ; Plot
Send('B,C{ENTER}')
MouseClick('left', $x + 73, $y + 376) ; SHIFT
Send('{F4}{F6}{F1}{F1}') ; Plot
Send('D,E{ENTER}')
Send('A=1')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
MouseClick('left', $x + 73, $y + 376) ; SHIFT
Send('{F4}{F6}{F2}{F1}') ; Line
Send('{ENTER}')
Send('A=2')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
MouseClick('left', $x + 73, $y + 376) ; SHIFT
Send('{F4}{F6}{F2}{F1}') ; Line
Send('{ENTER}')
Send('A=3')
MouseClick('left', $x + 73, $y + 376) ; SHIFT (state is PRGM)
MouseClick('left', $x + 159, $y + 376) ; PRGM (state is PRGM)
Send('{F3}') ; JUMP (state is ["PRGM", "JUMP"])
Send('{F3}') ; => (state is ["PRGM", "JUMP"])
MouseClick('left', $x + 73, $y + 376) ; SHIFT
Send('{F4}{F6}{F2}{F1}') ; Line
Send('{ENTER}')

; end program text

MouseClick('left', $x + 73, $y + 376) ; SHIFT
MouseClick('left', $x + 202, $y + 413) ; QUIT
Send('{F1}') ; EXE
