/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.bradders.casiocfx9800g.analysis;

import java.util.*;
import org.bradders.casiocfx9800g.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inASingleProgram(ASingleProgram node)
    {
        defaultIn(node);
    }

    public void outASingleProgram(ASingleProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleProgram(ASingleProgram node)
    {
        inASingleProgram(node);
        if(node.getStatementSeparator() != null)
        {
            node.getStatementSeparator().apply(this);
        }
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outASingleProgram(node);
    }

    public void inASequenceProgram(ASequenceProgram node)
    {
        defaultIn(node);
    }

    public void outASequenceProgram(ASequenceProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASequenceProgram(ASequenceProgram node)
    {
        inASequenceProgram(node);
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        if(node.getStatementSeparator() != null)
        {
            node.getStatementSeparator().apply(this);
        }
        if(node.getStatement() != null)
        {
            node.getStatement().apply(this);
        }
        outASequenceProgram(node);
    }

    public void inAPrinttextStatement(APrinttextStatement node)
    {
        defaultIn(node);
    }

    public void outAPrinttextStatement(APrinttextStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrinttextStatement(APrinttextStatement node)
    {
        inAPrinttextStatement(node);
        if(node.getQuotedText() != null)
        {
            node.getQuotedText().apply(this);
        }
        outAPrinttextStatement(node);
    }

    public void inAAssignStatement(AAssignStatement node)
    {
        defaultIn(node);
    }

    public void outAAssignStatement(AAssignStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignStatement(AAssignStatement node)
    {
        inAAssignStatement(node);
        if(node.getPrintResult() != null)
        {
            node.getPrintResult().apply(this);
        }
        if(node.getVariableName() != null)
        {
            node.getVariableName().apply(this);
        }
        if(node.getAssignArrow() != null)
        {
            node.getAssignArrow().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAAssignStatement(node);
    }

    public void inAPrintvalStatement(APrintvalStatement node)
    {
        defaultIn(node);
    }

    public void outAPrintvalStatement(APrintvalStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintvalStatement(APrintvalStatement node)
    {
        inAPrintvalStatement(node);
        if(node.getPrintResult() != null)
        {
            node.getPrintResult().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAPrintvalStatement(node);
    }

    public void inALabelStatement(ALabelStatement node)
    {
        defaultIn(node);
    }

    public void outALabelStatement(ALabelStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALabelStatement(ALabelStatement node)
    {
        inALabelStatement(node);
        if(node.getNumberLiteral() != null)
        {
            node.getNumberLiteral().apply(this);
        }
        if(node.getLabel() != null)
        {
            node.getLabel().apply(this);
        }
        outALabelStatement(node);
    }

    public void inAGotoStatement(AGotoStatement node)
    {
        defaultIn(node);
    }

    public void outAGotoStatement(AGotoStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGotoStatement(AGotoStatement node)
    {
        inAGotoStatement(node);
        if(node.getNumberLiteral() != null)
        {
            node.getNumberLiteral().apply(this);
        }
        if(node.getGoto() != null)
        {
            node.getGoto().apply(this);
        }
        outAGotoStatement(node);
    }

    public void inATermExpression(ATermExpression node)
    {
        defaultIn(node);
    }

    public void outATermExpression(ATermExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermExpression(ATermExpression node)
    {
        inATermExpression(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outATermExpression(node);
    }

    public void inAPlusExpression(APlusExpression node)
    {
        defaultIn(node);
    }

    public void outAPlusExpression(APlusExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusExpression(APlusExpression node)
    {
        inAPlusExpression(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outAPlusExpression(node);
    }

    public void inAMinusExpression(AMinusExpression node)
    {
        defaultIn(node);
    }

    public void outAMinusExpression(AMinusExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusExpression(AMinusExpression node)
    {
        inAMinusExpression(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outAMinusExpression(node);
    }

    public void inANegateExpression(ANegateExpression node)
    {
        defaultIn(node);
    }

    public void outANegateExpression(ANegateExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegateExpression(ANegateExpression node)
    {
        inANegateExpression(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        outANegateExpression(node);
    }

    public void inAFactorTerm(AFactorTerm node)
    {
        defaultIn(node);
    }

    public void outAFactorTerm(AFactorTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFactorTerm(AFactorTerm node)
    {
        inAFactorTerm(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAFactorTerm(node);
    }

    public void inAMultTerm(AMultTerm node)
    {
        defaultIn(node);
    }

    public void outAMultTerm(AMultTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultTerm(AMultTerm node)
    {
        inAMultTerm(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outAMultTerm(node);
    }

    public void inADivTerm(ADivTerm node)
    {
        defaultIn(node);
    }

    public void outADivTerm(ADivTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivTerm(ADivTerm node)
    {
        inADivTerm(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outADivTerm(node);
    }

    public void inASingleFactor(ASingleFactor node)
    {
        defaultIn(node);
    }

    public void outASingleFactor(ASingleFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleFactor(ASingleFactor node)
    {
        inASingleFactor(node);
        if(node.getMultgroup() != null)
        {
            node.getMultgroup().apply(this);
        }
        outASingleFactor(node);
    }

    public void inAMultgroupFactor(AMultgroupFactor node)
    {
        defaultIn(node);
    }

    public void outAMultgroupFactor(AMultgroupFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultgroupFactor(AMultgroupFactor node)
    {
        inAMultgroupFactor(node);
        if(node.getMultgroup() != null)
        {
            node.getMultgroup().apply(this);
        }
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAMultgroupFactor(node);
    }

    public void inAAtomMultgroup(AAtomMultgroup node)
    {
        defaultIn(node);
    }

    public void outAAtomMultgroup(AAtomMultgroup node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtomMultgroup(AAtomMultgroup node)
    {
        inAAtomMultgroup(node);
        if(node.getAtom() != null)
        {
            node.getAtom().apply(this);
        }
        outAAtomMultgroup(node);
    }

    public void inAPowerMultgroup(APowerMultgroup node)
    {
        defaultIn(node);
    }

    public void outAPowerMultgroup(APowerMultgroup node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPowerMultgroup(APowerMultgroup node)
    {
        inAPowerMultgroup(node);
        if(node.getAtom() != null)
        {
            node.getAtom().apply(this);
        }
        if(node.getPow() != null)
        {
            node.getPow().apply(this);
        }
        if(node.getMultgroup() != null)
        {
            node.getMultgroup().apply(this);
        }
        outAPowerMultgroup(node);
    }

    public void inAVarAtom(AVarAtom node)
    {
        defaultIn(node);
    }

    public void outAVarAtom(AVarAtom node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarAtom(AVarAtom node)
    {
        inAVarAtom(node);
        if(node.getVariableName() != null)
        {
            node.getVariableName().apply(this);
        }
        outAVarAtom(node);
    }

    public void inANumberAtom(ANumberAtom node)
    {
        defaultIn(node);
    }

    public void outANumberAtom(ANumberAtom node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberAtom(ANumberAtom node)
    {
        inANumberAtom(node);
        if(node.getNumberLiteral() != null)
        {
            node.getNumberLiteral().apply(this);
        }
        outANumberAtom(node);
    }

    public void inAInputAtom(AInputAtom node)
    {
        defaultIn(node);
    }

    public void outAInputAtom(AInputAtom node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInputAtom(AInputAtom node)
    {
        inAInputAtom(node);
        if(node.getInputPrompt() != null)
        {
            node.getInputPrompt().apply(this);
        }
        outAInputAtom(node);
    }

    public void inAExpressionAtom(AExpressionAtom node)
    {
        defaultIn(node);
    }

    public void outAExpressionAtom(AExpressionAtom node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpressionAtom(AExpressionAtom node)
    {
        inAExpressionAtom(node);
        if(node.getRparen() != null)
        {
            node.getRparen().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getLparen() != null)
        {
            node.getLparen().apply(this);
        }
        outAExpressionAtom(node);
    }

    public void inAFuncAtom(AFuncAtom node)
    {
        defaultIn(node);
    }

    public void outAFuncAtom(AFuncAtom node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncAtom(AFuncAtom node)
    {
        inAFuncAtom(node);
        if(node.getRparen() != null)
        {
            node.getRparen().apply(this);
        }
        if(node.getArgumentList() != null)
        {
            node.getArgumentList().apply(this);
        }
        if(node.getLparen() != null)
        {
            node.getLparen().apply(this);
        }
        if(node.getFunctionName() != null)
        {
            node.getFunctionName().apply(this);
        }
        outAFuncAtom(node);
    }

    public void inAFactorialAtom(AFactorialAtom node)
    {
        defaultIn(node);
    }

    public void outAFactorialAtom(AFactorialAtom node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFactorialAtom(AFactorialAtom node)
    {
        inAFactorialAtom(node);
        if(node.getBang() != null)
        {
            node.getBang().apply(this);
        }
        if(node.getAtom() != null)
        {
            node.getAtom().apply(this);
        }
        outAFactorialAtom(node);
    }

    public void inASingleArgumentList(ASingleArgumentList node)
    {
        defaultIn(node);
    }

    public void outASingleArgumentList(ASingleArgumentList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleArgumentList(ASingleArgumentList node)
    {
        inASingleArgumentList(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outASingleArgumentList(node);
    }

    public void inASequenceArgumentList(ASequenceArgumentList node)
    {
        defaultIn(node);
    }

    public void outASequenceArgumentList(ASequenceArgumentList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASequenceArgumentList(ASequenceArgumentList node)
    {
        inASequenceArgumentList(node);
        if(node.getArgumentList() != null)
        {
            node.getArgumentList().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outASequenceArgumentList(node);
    }
}
